// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK4uNHqzuwViDLyHX9YjPCHjT1e1NvEf0',
    appId: '1:943878807934:web:2c0efa4750f7a7b7ea932f',
    messagingSenderId: '943878807934',
    projectId: 'fir-test-8f5df',
    authDomain: 'fir-test-8f5df.firebaseapp.com',
    storageBucket: 'fir-test-8f5df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC82Pz437vwvC7Dqou99TXuvroefTb2vJ8',
    appId: '1:943878807934:android:3c5f3b68766c055dea932f',
    messagingSenderId: '943878807934',
    projectId: 'fir-test-8f5df',
    storageBucket: 'fir-test-8f5df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqzN5pvccWgF8q2BywS-JYVmFpJ46oQXw',
    appId: '1:943878807934:ios:f79b5adf4730daa3ea932f',
    messagingSenderId: '943878807934',
    projectId: 'fir-test-8f5df',
    storageBucket: 'fir-test-8f5df.appspot.com',
    iosBundleId: 'com.example.appFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqzN5pvccWgF8q2BywS-JYVmFpJ46oQXw',
    appId: '1:943878807934:ios:337fc9c7a04da429ea932f',
    messagingSenderId: '943878807934',
    projectId: 'fir-test-8f5df',
    storageBucket: 'fir-test-8f5df.appspot.com',
    iosBundleId: 'com.example.appFirebase.RunnerTests',
  );
}
